#!/usr/bin/env nix-shell
#!nix-shell -i bash -p bash curl jq

# Exit early if there are any errors
set -o errexit

# Inputs
MINECRAFT_VERSION="$1"
LOADER_VERSION="$2"

# Input Validation
if [ -z "$MINECRAFT_VERSION" ] || [ -z "$LOADER_VERSION" ]; then
	>&2 echo "USAGE: ${BASH_SOURCE[0]} <MINECRAFT_VERSION> <LOADER_VERSION>"
	exit 1
fi

# Print the lockfile to `stdout`
URL="https://meta.fabricmc.net/v2/versions/loader/$MINECRAFT_VERSION/$LOADER_VERSION/server/json"

curl "$URL" \
| jq -r '
  .mainClass,
  (.libraries[]
  | .url as $url
  | .name | split(":") as [$dir, $name, $version]
  |"\($name)-\($version).zip|\($url)\($dir|sub("\\.";"/";"g"))/\($name)/\($version)/\($name)-\($version).jar"
  )' \
| {
    echo '# This file was @generated by `generate-lock.sh`.'
    echo "# The source URL for this information was: $URL"
    echo "{"
    echo "  minecraftVersion = \"$MINECRAFT_VERSION\";"
    echo "  loaderVersion = \"$LOADER_VERSION\";"
    read mainClass;
    echo "  mainClass = \"$mainClass\";"
    echo "  libraries = ["
    while IFS="|" read name url; do
        hash=$(nix-prefetch-url $url);
        echo "    { name = \"$name\"; url = \"$url\"; sha256 = \"$hash\"; }"
    done
    echo "  ];"
    echo "}"
}
