# This file was @generated by `generate-lock.sh`.
# The source URL for this information was: https://meta.fabricmc.net/v2/versions/loader/1.21.1/0.16.9/server/json
{
  minecraftVersion = "1.21.1";
  loaderVersion = "0.16.9";
  mainClass = "net.fabricmc.loader.impl.launch.knot.KnotServer";
  libraries = [
    {
      name = "asm";
      version = "9.7.1";
      fileName = "asm-9.7.1.zip";
      url = "https://maven.fabricmc.net/org/ow2/asm/asm/9.7.1/asm-9.7.1.jar";
      sha256 = "109jf45p87689kmyvirrj6xl180pp4wcmv7s0pg0jvgbqlxd9bcc";
    }
    {
      name = "asm-analysis";
      version = "9.7.1";
      fileName = "asm-analysis-9.7.1.zip";
      url = "https://maven.fabricmc.net/org/ow2/asm/asm-analysis/9.7.1/asm-analysis-9.7.1.jar";
      sha256 = "1why0hpcq71xp8p1arvs4v1p5q945hy348nzdsvip8sbi1qr7cl5";
    }
    {
      name = "asm-commons";
      version = "9.7.1";
      fileName = "asm-commons-9.7.1.zip";
      url = "https://maven.fabricmc.net/org/ow2/asm/asm-commons/9.7.1/asm-commons-9.7.1.jar";
      sha256 = "1866vv6lj45xkd2kmb5mqa95aqwwfga3ycflf7hrpbcjs9a9nmws";
    }
    {
      name = "asm-tree";
      version = "9.7.1";
      fileName = "asm-tree-9.7.1.zip";
      url = "https://maven.fabricmc.net/org/ow2/asm/asm-tree/9.7.1/asm-tree-9.7.1.jar";
      sha256 = "07xlsg1932cp81xgsvaf20fp5kjrgg3p0ifmhq788szbb4gqhacr";
    }
    {
      name = "asm-util";
      version = "9.7.1";
      fileName = "asm-util-9.7.1.zip";
      url = "https://maven.fabricmc.net/org/ow2/asm/asm-util/9.7.1/asm-util-9.7.1.jar";
      sha256 = "1ij3rg1vxpg4dxk4cza9gh2rd6xjfs94y75dy7smc1f9nmqvx1gq";
    }
    {
      name = "sponge-mixin";
      version = "0.15.4+mixin.0.8.7";
      fileName = "sponge-mixin-0.15.4+mixin.0.8.7.zip";
      url = "https://maven.fabricmc.net/net/fabricmc/sponge-mixin/0.15.4+mixin.0.8.7/sponge-mixin-0.15.4+mixin.0.8.7.jar";
      sha256 = "18n2c8hri5szfz64m8d66wpmwr408vgsg1g2wv4jmbl0m5yzcca6";
    }
    {
      name = "intermediary";
      version = "1.21.1";
      fileName = "intermediary-1.21.1.zip";
      url = "https://maven.fabricmc.net/net/fabricmc/intermediary/1.21.1/intermediary-1.21.1.jar";
      sha256 = "1yinma2ybq29k3wc52dj8v9vf1309zvh8w39a70nwlsazdyianb0";
    }
    {
      name = "fabric-loader";
      version = "0.16.9";
      fileName = "fabric-loader-0.16.9.zip";
      url = "https://maven.fabricmc.net/net/fabricmc/fabric-loader/0.16.9/fabric-loader-0.16.9.jar";
      sha256 = "1ypi662al3fz2g1075dsj348xbaf1rz4zkzyd2wnnb75krgd1cdi";
    }
  ];
}
