# This file was @generated by `generate-lock.sh`.
# The source URL for this information was: https://meta.fabricmc.net/v2/versions/loader/1.21.1/0.16.14/server/json
{
  minecraftVersion = "1.21.1";
  loaderVersion = "0.16.14";
  mainClass = "net.fabricmc.loader.impl.launch.knot.KnotServer";
  libraries = [
    {
      name = "asm";
      version = "9.8";
      fileName = "asm-9.8.zip";
      url = "https://maven.fabricmc.net/org/ow2/asm/asm/9.8/asm-9.8.jar";
      sha256 = "0l90a8bxxv49m6kzrwccxdd7pjb3n2mzrfbylrfavv6shdmanvl7";
    }
    {
      name = "asm-analysis";
      version = "9.8";
      fileName = "asm-analysis-9.8.zip";
      url = "https://maven.fabricmc.net/org/ow2/asm/asm-analysis/9.8/asm-analysis-9.8.jar";
      sha256 = "1fgd146yxz1dcb495gzv9n7ni143wcjz21554lcjginkphpp6h76";
    }
    {
      name = "asm-commons";
      version = "9.8";
      fileName = "asm-commons-9.8.zip";
      url = "https://maven.fabricmc.net/org/ow2/asm/asm-commons/9.8/asm-commons-9.8.jar";
      sha256 = "1x04fkkxz31vhy4bxpv7y30d9bn5sz0xlj16572zqnacrg0s209k";
    }
    {
      name = "asm-tree";
      version = "9.8";
      fileName = "asm-tree-9.8.zip";
      url = "https://maven.fabricmc.net/org/ow2/asm/asm-tree/9.8/asm-tree-9.8.jar";
      sha256 = "1warmm4ms2f4qi6qjsiaadsk5f7zqcpl64173q8fspn8nw68idql";
    }
    {
      name = "asm-util";
      version = "9.8";
      fileName = "asm-util-9.8.zip";
      url = "https://maven.fabricmc.net/org/ow2/asm/asm-util/9.8/asm-util-9.8.jar";
      sha256 = "05cdl23vaxfw7fjq2zq7pibs84x56csfzwz5h0lhxz98rc74d84b";
    }
    {
      name = "sponge-mixin";
      version = "0.15.5+mixin.0.8.7";
      fileName = "sponge-mixin-0.15.5+mixin.0.8.7.zip";
      url = "https://maven.fabricmc.net/net/fabricmc/sponge-mixin/0.15.5+mixin.0.8.7/sponge-mixin-0.15.5+mixin.0.8.7.jar";
      sha256 = "114mb6qks1s7mnpyy0vigaqmdnc61mlxj1vbdg73na6mirvjpp81";
    }
    {
      name = "intermediary";
      version = "1.21.1";
      fileName = "intermediary-1.21.1.zip";
      url = "https://maven.fabricmc.net/net/fabricmc/intermediary/1.21.1/intermediary-1.21.1.jar";
      sha256 = "1yinma2ybq29k3wc52dj8v9vf1309zvh8w39a70nwlsazdyianb0";
    }
    {
      name = "fabric-loader";
      version = "0.16.14";
      fileName = "fabric-loader-0.16.14.zip";
      url = "https://maven.fabricmc.net/net/fabricmc/fabric-loader/0.16.14/fabric-loader-0.16.14.jar";
      sha256 = "1h7g0gq3wpz4bh1lp4q0qvqfi2c92kcrqjqvsybsslvi37sbgmwy";
    }
  ];
}
