# This file was @generated by `generate-lock.sh`.
# The source URL for this information was: https://meta.fabricmc.net/v2/versions/loader/1.20.4/0.15.10/server/json
{
  minecraftVersion = "1.20.4";
  loaderVersion = "0.15.10";
  mainClass = "net.fabricmc.loader.impl.launch.knot.KnotServer";
  libraries = [
    {
      name = "asm-9.6.zip";
      url = "https://maven.fabricmc.net/org/ow2/asm/asm/9.6/asm-9.6.jar";
      sha256 = "18834cy0i1zqffb336p16li5ag4w3lylx7v67f2llgfv4hjaqvrw";
    }
    {
      name = "asm-analysis-9.6.zip";
      url = "https://maven.fabricmc.net/org/ow2/asm/asm-analysis/9.6/asm-analysis-9.6.jar";
      sha256 = "1fyvivkgmabvrgnp2rks6cp687dk31hsqn951v30gp3yqgbk4a6r";
    }
    {
      name = "asm-commons-9.6.zip";
      url = "https://maven.fabricmc.net/org/ow2/asm/asm-commons/9.6/asm-commons-9.6.jar";
      sha256 = "04f5axvch7vqqlbsmrrcmwrvxdjzfvdgw4vmkz3025whq3ax1vvs";
    }
    {
      name = "asm-tree-9.6.zip";
      url = "https://maven.fabricmc.net/org/ow2/asm/asm-tree/9.6/asm-tree-9.6.jar";
      sha256 = "1vz7i0w2imb7allfcgb8kb9y4xxkadjvidd7bphpgirrnlbwygn4";
    }
    {
      name = "asm-util-9.6.zip";
      url = "https://maven.fabricmc.net/org/ow2/asm/asm-util/9.6/asm-util-9.6.jar";
      sha256 = "1hy4zaa1k6zwvsd75s33rphhynh2cbm0q8zln9kbzaaa5x0afdf6";
    }
    {
      name = "sponge-mixin-0.13.3+mixin.0.8.5.zip";
      url = "https://maven.fabricmc.net/net/fabricmc/sponge-mixin/0.13.3+mixin.0.8.5/sponge-mixin-0.13.3+mixin.0.8.5.jar";
      sha256 = "01s6gvd24187zrzfz73s7rr9l40bb60w08gcnnssymbl5n9mzcvc";
    }
    {
      name = "intermediary-1.20.4.zip";
      url = "https://maven.fabricmc.net/net/fabricmc/intermediary/1.20.4/intermediary-1.20.4.jar";
      sha256 = "0ilbmyx39s5ldvy38gl0xvnijp1kg1fxgqjkn8xyhpfhh57iybz0";
    }
    {
      name = "fabric-loader-0.15.10.zip";
      url = "https://maven.fabricmc.net/net/fabricmc/fabric-loader/0.15.10/fabric-loader-0.15.10.jar";
      sha256 = "1v4d57ws0jpc5mpw9vnd29014d5l52pbpmv21n4gxvlhna7b4344";
    }
  ];
}
